### ISSUE TITLE
Sprawdzić zakres obrotu Dobota w pierwszej osi jak stoi przy bandzie

### ISSUE THREAD

**Issue by jkaniuka** [GroupOfRobots/HeROS-swarm#1]
Jak Dobot stanie przy bandzie to prawdopodobnie będzie miał ograniczony zakres ruchu wynikający z potencjalnych kolizji takich jak:

- tłok od chwytaka + banda
- silnik krokowy + banda

![image](https://github.com/GroupOfRobots/HeROS-swarm/assets/80155305/3ea28c59-94c2-472f-8394-32707e9b72c9)

**Comment by twiniars** [comment]
Ewentualnie można w tym obszarze niższą bandę dać

**Comment by jkaniuka** [comment]
- Silniki nie uderzają w bandę. 
- Aby tłok od chwytaka nie uderzał w bandę, strefa poboru kostek zostanie ograniczona.
