### ISSUE TITLE
Czujnik ToF do detekcji kostki na MiniRysiu

### ISSUE THREAD

**Issue by jkaniuka** [GroupOfRobots/HeROS-swarm#5]

**Comment by jkaniuka** [comment]
Alternatywnym rozwiązaniem może być wykrywanie kostki na MiniRysiu z pomocą LiDARu. Miejsce odkładania kostki planowane jest ~5cm od LiDARu (jego zasięg to 0.02-12 m).

**Comment by Kubaless** [comment]
Po wspólnych ustaleniach postanowiliśmy że kostka będzie wykrywana za pomocą lidaru.
